name: Build buildbot and build dependencies

on:
  pull_request:
    branches:
      - main
jobs:
  build-and-run:
    runs-on: [self-hosted, macOS]
    timeout-minutes: 10

    steps:
      - name: Clean Workspace
        run: |
          echo "Cleaning workspace..."
          shopt -s extglob
          rm -rf !( ".git" ) || true
          echo "Workspace cleaned."

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Xcode Project
        run: xcodebuild build -configuration Release

      - name: Run Executable
        working-directory: ${{ github.workspace }}
        run: |
          chmod +x build/Release/iosbuildbot
          ./build/Release/iosbuildbot
